INSERT INTO cars (make, model, year, color, litre, mileage, price, condition, seller) VALUES ('Audi', 'A4', 1999, 'Red', 1.8, 91300, 3000, 'USED', 'sregan22');
INSERT INTO cars (make, model, year, color, litre, mileage, price, condition, seller) VALUES ('Opel', 'Astra', 2000, 'Silver', 1.4, 88000, 1900, 'USED', 'cfarr');
INSERT INTO cars (make, model, year, color, litre, mileage, price, condition, seller) VALUES ('Toyota', 'Avensis', 2006, 'Silver', 1.6, 34500, 9400, 'USED', 'cfarr');
INSERT INTO cars (make, model, year, color, litre, mileage, price, condition, seller) VALUES ('Citroen', 'C4 Picasso', 2007, 'Black', 1.4, 36000, 7950, 'USED', 'jthomas');
INSERT INTO cars (make, model, year, color, litre, mileage, price, condition, seller) VALUES ('Seat', 'Cordoba', 2008, 'Silver', 1.2, 26000, 6000, 'USED', 'sanjesh');
INSERT INTO cars (make, model, year, color, litre, mileage, price, condition, seller) VALUES ('Ford', 'Fiesta', 2007, 'Blue', 1.1, 41000, 5500, 'USED', 'granger10');
INSERT INTO cars (make, model, year, color, litre, mileage, price, condition, seller) VALUES ('Ford', 'Focus', 2000, 'Red', 1.4, 103000, 3000, 'USED', 'jthomas');
INSERT INTO cars (make, model, year, color, litre, mileage, price, condition, seller) VALUES ('Ford', 'Focus', 2013, 'Blue', 1.9, 11000, 17000, 'USED', 'jthomas');
INSERT INTO cars (make, model, year, color, litre, mileage, price, condition, seller) VALUES ('Subaru', 'Impreza', 2003, 'Blue', 2, 70400, 8000, 'USED', 'dunne111');
INSERT INTO cars (make, model, year, color, litre, mileage, price, condition, seller) VALUES ('Mazda', '3', 2006, 'Grey', 1.8, 74000, 9800, 'USED', 'sregan22');
INSERT INTO cars (make, model, year, color, litre, mileage, price, condition, seller) VALUES ('Renault', 'Megane', 2001, 'Blue', 1.6, 114000, 2800, 'USED', 'sitko');
INSERT INTO cars (make, model, year, color, litre, mileage, price, condition, seller) VALUES ('Audi', 'A4', 2016, 'Red', 2, 0, 51000, 'NEW', 'sitko');
INSERT INTO cars (make, model, year, color, litre, mileage, price, condition, seller) VALUES ('Honda', 'Accord', 2016, 'Silver', 2.2, 0, 38000, 'NEW', 'granger10');
INSERT INTO cars (make, model, year, color, litre, mileage, price, condition, seller) VALUES ('Volvo', 'C70', 2016, 'Brown', 1.8, 0, 41000, 'NEW', 'sanjesh');
INSERT INTO cars (make, model, year, color, litre, mileage, price, condition, seller) VALUES ('Mercedes', 'C-Class', 2016, 'White', 3.2, 0, 59000, 'NEW', 'granger10');
INSERT INTO cars (make, model, year, color, litre, mileage, price, condition, seller) VALUES ('Mini', 'Cooper', 2016, 'Black', 1.6, 0, 38000, 'NEW', 'jthomas');
INSERT INTO cars (make, model, year, color, litre, mileage, price, condition, seller) VALUES ('Hyundai', 'Santa Fe', 2016, 'Silver', 2.4, 0, 36000, 'NEW', 'ellen101');
INSERT INTO cars (make, model, year, color, litre, mileage, price, condition, seller) VALUES ('Volkswagen', 'Touareg', 2016, 'Silver', 2, 0, 43000, 'NEW', 'sanjesh');
INSERT INTO cars (make, model, year, color, litre, mileage, price, condition, seller) VALUES ('Dodge', 'Challenger', 2010, 'Red', 3.2, 8500, 34500, 'USED', 'sitko');
INSERT INTO cars (make, model, year, color, litre, mileage, price, condition, seller) VALUES ('BMW', 'Series 5', 2016, 'White', 3.2, 0, 58000, 'NEW', 'sitko');